### ISSUE TITLE
Missing Entities

### ISSUE THREAD

**Issue by jasonyates** [tube0013/Smartcar-HA#5]
I can see from the logs in Smartcar that the integration is successfully pulling various enpoints such as Fuel Tank, Odometer, Lock Status, Tyre Pressure however I only have the Odometer entity created in HA.

**Comment by tube0013** [comment]
Hi, can you enable debug logging for the integration -

```
logger:
  default: info
  logs:
    custom_components.smartcar: debug
```
deleted and then re-add the integration. post the logs here, (please redact VIN and any other ID's that show)

thanks

**Comment by wbyoung** [comment]
I may have this fixed in https://github.com/tube0013/Smartcar-HA/pull/9. Let me know if you'd like help trying it out.

**Comment by jasonyates** [comment]
Can you release a new version of the addon so that I can update and test?

**Comment by tube0013** [comment]
I just pushed a new release

**Comment by jasonyates** [comment]
Thanks, that looks much better.

I still have an issue with Fuel though despite the Smartcar API returning fuel data for my vehicle.
